temp<-tempfile()
download.file(url="https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)
data<-read.table(unz(temp, "household_power_consumption.txt"),sep=";")
unlink(temp)
feb1and2data<-data[data$V1=="1/2/2007"|data$V1=="2/2/2007",]
merged.date.and.time<-paste(feb1and2data[,1],feb1and2data[,2])
date.and.time<-strptime(merged.date.and.time,format="%d/%m/%Y %H:%M:%S")
sub1<-as.numeric(as.character(feb1and2data[,7]))
sub2<-as.numeric(as.character(feb1and2data[,8]))
sub3<-as.numeric(as.character(feb1and2data[,9]))
global.active.power<-as.numeric(as.character(feb1and2data[,3]))
global.reactive.power<-as.numeric(as.character(feb1and2data[,4]))
voltage<-as.numeric(as.character(feb1and2data[,5]))
par(mfrow=c(2,2))
plot(date.and.time,global.active.power,xlab="",ylab="Global Active Power",type="l")
plot(date.and.time,voltage,xlab="datetime",ylab="Voltage",type="l")
plot(date.and.time,sub1,type="n",ylab="Energy sub metering",xlab="")
points(date.and.time,sub1,col="black",type="l")
points(date.and.time,sub2,col="red",type="l")
points(date.and.time,sub3,col="blue",type="l")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"))
plot(date.and.time,global.reactive.power,xlab="datetime",ylab="Global_reactive_power",type="l")
dev.copy(png, file = "plot4.png")
dev.off()